version: "3.8"

services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_DB=betlive24
      - POSTGRES_USER=betlive24Admin
      - POSTGRES_PASSWORD=betlive24123456
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
